backend/api/urls.py
from django.urls import path 
from .views import *
from django.urls import path
from .views import register, LoginView, LogoutView
from knox import views as knox_views

app_name = 'api'

# define the urls
urlpatterns = [
    path('all_set/', card_set, name="card-set"),
    # path('tasks/<int:pk>/', card_set),
    path('create_set/', create_card_set, name='create-card-set'),
    path('delete_set/<int:pk>', delete_card_set, name='delete-card-set'),
    path('set_updated/<int:pk>', update_cardset, name='cupdate_cardset'),
    path('set_checked/<int:pk>', cardset_checked_view, name='cardset-checked-view'),
    path('register/', register, name='register'),
    path('login/', LoginView.as_view(), name='knox_login'),
    path('logout/', LogoutView.as_view(), name='knox_logout'),
    # path('logoutall/', knox_views.LogoutAllView.as_view(), name='knox_logoutall'),
]

backend/cards/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'cards'

urlpatterns = [
    # path("", TemplateView.as_view(template_name="cards/base.html"), name="home"),
    path("", views.CardListView.as_view(), name="card-list"),
    path("<int:pk>", views.SetListView.as_view(), name="set-list"),
    path("set_change", views.set_change, name='set_change'),
    path("new", views.CardCreateView.as_view(), name="card-create"),
    path("edit/<int:pk>", views.CardUpdateView.as_view(), name="card-update"),
    path("box/<int:box_num>",views.BoxView.as_view(), name="box"),
]

backend/flashcards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("cards.urls")),
    path('api/', include('api.urls')),
]

backend/cards/models.py
from django.db import models


class CardSets(models.Model):
    set_name = models.CharField(max_length=100)
    set_description = models.CharField(max_length=200, default="")
    checked = models.BooleanField(default=0)
    def __str__(self):
        return  self.set_name

NUM_BOXES = 5
BOXES = range(1, NUM_BOXES + 1)

class Card(models.Model):
    card_set = models.ForeignKey(CardSets, on_delete=models.CASCADE)
    question = models.CharField(max_length=100, default="")
    answer = models.CharField(max_length=100, default="")
    box = models.IntegerField(
        choices=zip(BOXES, BOXES),
        default=BOXES[0],
    )
    date_created = models.DateTimeField(auto_now_add=True)

    def move(self, solved):
        new_box = self.box + 1 if solved else BOXES[0]
        if new_box in BOXES:
            self.box = new_box
            self.save()
        return self

    def __str__(self):
        return self.question

backend/cards/forms.py
from django import forms
from .models import Card

class CardCheckForm(forms.Form):
    card_id = forms.IntegerField(required=True)
    solved = forms.BooleanField(required=False)

class ChangeSetForm(forms.ModelForm):
    """  Hier may set the Card-set """
    class Meta:
        model = Card
        fields = ('card_set', )

backend/cards/views.py
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render
import random
from django.views.generic import ListView, CreateView, UpdateView
from .forms import CardCheckForm, ChangeSetForm

from .models import Card, CardSets

def set_change(request):   
    if request.method == "POST":
        form = ChangeSetForm(request.POST)
        if form.is_valid():
            choice = form.save(commit=False)
            pk = choice.card_set.id
            return redirect('cards:set-list', pk=pk,  )
        else:
            context = {'choice': "Fault"}
            return render(request, 'cards:set-list', context )
        print(context)
    else:
        form = ChangeSetForm()
    return render(request, 'cards/card_set_form.html', {'form': form})

class CardListView(ListView):
    model = Card
    queryset = Card.objects.all().order_by("box", "-date_created")


class SetListView(ListView):
    model = Card
    
    def get_queryset(self):
        card_set = get_object_or_404(CardSets, pk=self.kwargs["pk"])
        return Card.objects.filter(card_set=self.kwargs["pk"]).order_by("box", "-date_created")


class CardCreateView(CreateView):
    model = Card
    fields = ["card_set", "question", "answer", "box"]
    success_url = reverse_lazy("card-create")


class CardUpdateView(CardCreateView, UpdateView):
    success_url = reverse_lazy("card-list")


class BoxView(CardListView):
    template_name = "cards/box.html"
    form_class = CardCheckForm

    def get_queryset(self):
        return Card.objects.filter(box=self.kwargs["box_num"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["box_number"] = self.kwargs["box_num"]
        if self.object_list:
            context["check_card"] = random.choice(self.object_list)
        return context
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            card = get_object_or_404(Card, id=form.cleaned_data["card_id"])
            card.move(form.cleaned_data["solved"])

        return redirect(request.META.get("HTTP_REFERER"))

backend/cards/templates/cards/base.html
<!DOCTYPE html>
<!-- {% load static %} --> 
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Flashcards</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
        <!-- <link rel="stylesheet" href="{% static 'css/blog.css' %}"> -->
    </head>

    <style>
        /* Custom CSS */

        :root {
            --accent: #6e48ad;
            --accent-bg: white;
            --bg: #fff;
            --text: #212121;
            --text-light: #585858;
            --border: #d8dae1;
            --code: #d81b60;
            --preformatted: #444;
        }

        article {
            background-color: var(--marked);
            border: 1px solid var(--border);
            border-radius: 5px;
            padding: 1em;
            margin: 1em 0;
        }

        h2 {
            text-align: center;
        }

        h2, h4 {
            margin-top: 0;
        }

        hr {
            background: var(--accent);
            border-color: var(--accent);
        }

        button,
        a[role="button"] {
            color: white;
            text-decoration: none;
        }

        input, select, textarea {
            width: 100%;
        }
    </style>

    <body>
        <header>
            <h1>Flashcards App</h1>
            {% include "cards/navigation.html" %}
        </header>
        
        <main>
            {% block content %}
                <!-- <h2>Welcome to your Flashcards app!</h2> -->
            {% endblock content %}
        </main>
    </body>
</html>

backend/cards/templates/cards/box.html
<!DOCTYPE htm>
{% extends "cards/base.html" %}
{% load humanize %}

{% block content %}
    <h2>🗃 {{ box_number | ordinal }} Box</h2>
    <mark>{{ object_list | length }}</mark> Card{{ object_list | pluralize }} left in box.
    <hr>
    {% if check_card %}
        {% include "cards/card.html" with card=check_card %}
    {% endif %}
{% endblock content %}

backend/cards/templates/cards/box_links.html
<!DOCTYPE htm>
{% load humanize %}

{% for box in boxes %}
    <a href="{% url 'cards:box' box_num=box.number %}">
        🗃 {{ box.number | ordinal }} Box <mark>{{ box.card_count }}</mark>
    </a>
{% endfor %}

backend/cards/templates/cards/card.html
<!DOCTYPE htm>
<article>
    <div class="row">
        <div class="col-md-6">
            <h4>{{ card.question }}</h4>
        </div>
        <div class="col-md-6">
            <p style="text-align: right;">{{ card.card_set }}</p>
        </div>

    </div>
    {% if not check_card %}
        <p>{{ card.answer }} </p>
        <hr>
        <a href="{% url 'cards:card-update' card.id %}" role="button">
            ✏️ Edit Card
        </a>
    {% else %}
        <details>
            <summary>Reveal Answer</summary>
            <p>{{ card.answer }}</p>
        </details>
        <hr>
        {% include "cards/card_check_form.html" with solved=True %}
        {% include "cards/card_check_form.html" with solved=False %}
    {% endif %}
</article>

 

backend/cards/templates/cards/card_check_form.html
<!DOCTYPE htm>
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="card_id" value="{{ card.id }}">
    <input type="hidden" name="solved" value="{{ solved }}">
    {% if solved %}
        <input type="submit" value="✅ I know"/>
    {% else %}
        <input type="submit" value="❌ I don't know"/>
    {% endif %}
</form>

backend/cards/templates/cards/card_form.html
<!DOCTYPE html>
{% extends "cards/base.html" %}

{% block content %}
    {% if card %}
        <h2>✏️ Edit Card</h2>
    {% else %}
        <h2>✨ Create New Card</h2>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save Card">
    </form>
    <a href="{% url 'cards:card-list' %}">
        Cancel
    </a>
{% endblock %}

backend/cards/templates/cards/card_list.html
<!DOCTYPE htm>
{% extends "cards/base.html" %}
{% load humanize %}

{% block content %}
    <h2>
        All {{card_list.0.card_set}} Cards
    </h2>
    <a href="{% url 'cards:card-create' %}" role="button">
        <h4 style="color:black">
            ✨ Create New Card 
        </h4>
    </a>
    {% for card in card_list %}
        {% ifchanged %}
            <h3>🗃 {{ card.box | ordinal }} Box</h3>
        {% endifchanged %}
        {% include "cards/card.html" %}
    {% endfor %}
{% endblock content %}

backend/cards/templates/cards/card_set_form.html
<!DOCTYPE htm>
{% extends "cards/base.html" %}

{% block content %}
<h1>Choose</h1>

<div class="input-group mb-3">
    
    <form method="POST" class="post-form">{% csrf_token %}
        <h4>{{form}}</h4>
        <button id="submit" type="submit" class="save btn btn-primary">Save Set</button>
        <a href="{% url 'cards:card-list' %}">
            <button type="button" class="btn btn-primary">
                All set
            </button>
        </a>
    </form>
</div>
{% endblock %}

backend/cards/templates/cards/navigation.html
<!DOCTYPE htm>
{% load cards_tags %}
<nav>
    <a href="{% url 'cards:set_change' %}">🗂️ All {{card_list.0.card_set}} Cards</a>
    {% boxes_as_links %}
</nav>